#!/usr/bin/env python3
"""Execute safe follow-up capture tasks from the viral material library."""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import urllib.parse
from datetime import date
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = ROOT / "scripts"
COMPETITOR_DIR = Path("reports/promotion-manager/competitors")
TODAY = date.today().isoformat()


def main() -> None:
    args = parse_args()
    out_dir = Path(args.out_dir)
    tasks_path = Path(args.tasks_json) if args.tasks_json else out_dir / COMPETITOR_DIR / "follow-up-capture-tasks.json"
    tasks = load_tasks(tasks_path, args.limit)
    results, deep_records = run_tasks(args, out_dir, tasks)
    write_outputs(out_dir, tasks_path, results, deep_records, args.dry_run)
    print(f"Follow-up capture results written to: {(report_dir(out_dir) / 'follow-up-capture-results.json').resolve()}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run safe public follow-up captures and create evidence requests for manual/browser-assisted tasks.")
    parser.add_argument("--tasks-json", default="", help="follow-up-capture-tasks.json generated by viral_content_library.py.")
    parser.add_argument("--out-dir", default="./promotion-output")
    parser.add_argument("--limit", type=int, default=20)
    parser.add_argument("--dry-run", action="store_true", help="Plan public captures without fetching URLs.")
    parser.add_argument("--allow-localhost", action="store_true", help="Allow localhost URLs for local fixtures/tests only.")
    return parser.parse_args()


def load_tasks(path: Path, limit: int) -> list[dict[str, Any]]:
    if not path.exists():
        return []
    try:
        data = json.loads(path.read_text(encoding="utf-8-sig"))
    except json.JSONDecodeError:
        return []
    tasks = data.get("tasks", []) if isinstance(data, dict) else []
    return [task for task in tasks if isinstance(task, dict)][: max(limit, 0)]


def run_tasks(args: argparse.Namespace, out_dir: Path, tasks: list[dict[str, Any]]) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    results = []
    deep_records = []
    for task in tasks:
        if task.get("mode") == "public_url_capture_candidate":
            result, records = run_public_capture(args, out_dir, task)
        else:
            result, records = create_evidence_request(out_dir, task), []
        results.append(result)
        deep_records.extend(records)
    return results, deep_records


def run_public_capture(args: argparse.Namespace, out_dir: Path, task: dict[str, Any]) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    url = str(task.get("url") or "")
    platform = str(task.get("platform") or "auto")
    task_id = safe_slug(str(task.get("id") or task.get("materialId") or "follow-up"))
    task_out_dir = report_dir(out_dir) / "follow-up-captures" / task_id
    validation_issue = validate_public_capture_url(url, args.allow_localhost)
    command = [
        sys.executable,
        str(SCRIPTS / "competitor_intake.py"),
        "--url",
        url,
        "--platform",
        platform,
        "--out-dir",
        str(task_out_dir),
    ]
    base = base_result(task, "public_url_capture_candidate", command)
    if validation_issue:
        base.update({"status": "blocked", "reason": validation_issue})
        return base, []
    if args.dry_run:
        base.update({"status": "dry_run", "reason": "Public capture planned but not executed because --dry-run was supplied."})
        return base, []

    result = subprocess.run(command, cwd=ROOT, capture_output=True, text=True, check=False)
    imported_path = task_out_dir / COMPETITOR_DIR / "imported-competitors.json"
    base.update(
        {
            "status": "ready" if result.returncode == 0 and imported_path.exists() else "error",
            "exitCode": result.returncode,
            "stdoutTail": tail(result.stdout),
            "stderrTail": tail(result.stderr),
            "importedCompetitors": str(imported_path) if imported_path.exists() else "",
        }
    )
    records = records_from_import(imported_path, task)
    base["recordCount"] = len(records)
    return base, records


def create_evidence_request(out_dir: Path, task: dict[str, Any]) -> dict[str, Any]:
    task_id = safe_slug(str(task.get("id") or task.get("materialId") or "follow-up"))
    request_dir = report_dir(out_dir) / "follow-up-captures/manual-evidence"
    request_dir.mkdir(parents=True, exist_ok=True)
    request_path = request_dir / f"{task_id}.md"
    request_path.write_text(render_evidence_request(task) + "\n", encoding="utf-8")
    result = base_result(task, str(task.get("mode") or "manual"), task.get("command") if isinstance(task.get("command"), list) else [])
    status = "blocked" if str(task.get("mode")) in {"manual_url_required", "unsupported_or_private_url"} else "queued_manual_evidence"
    result.update(
        {
            "status": status,
            "reason": task.get("reason") or "Manual or browser-visible evidence is required before deep capture.",
            "evidenceRequest": str(request_path),
            "recordCount": 0,
        }
    )
    return result


def records_from_import(path: Path, task: dict[str, Any]) -> list[dict[str, Any]]:
    if not path.exists():
        return []
    try:
        report = json.loads(path.read_text(encoding="utf-8-sig"))
    except json.JSONDecodeError:
        return []
    records = []
    for record in report.get("records", []):
        if not isinstance(record, dict):
            continue
        enriched = dict(record)
        enriched["sourceFollowUpTask"] = {
            "id": task.get("id"),
            "materialId": task.get("materialId"),
            "priority": task.get("priority"),
            "title": task.get("title"),
            "url": task.get("url"),
        }
        records.append(enriched)
    return records


def write_outputs(out_dir: Path, tasks_path: Path, results: list[dict[str, Any]], deep_records: list[dict[str, Any]], dry_run: bool) -> None:
    directory = report_dir(out_dir)
    directory.mkdir(parents=True, exist_ok=True)
    result_report = {
        "generatedAt": TODAY,
        "tasksJson": str(tasks_path),
        "dryRun": dry_run,
        "recordCount": len(results),
        "results": results,
        "summary": summarize_results(results),
        "guardrails": guardrails(),
    }
    deep_report = {
        "generatedAt": TODAY,
        "recordCount": len(deep_records),
        "records": deep_records,
        "aggregatePatterns": aggregate_deep_records(deep_records),
        "guardrails": guardrails(),
    }
    (directory / "follow-up-capture-results.json").write_text(json.dumps(result_report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    (directory / "follow-up-capture-results.md").write_text(render_results_markdown(result_report) + "\n", encoding="utf-8")
    (directory / "deep-competitor-library.json").write_text(json.dumps(deep_report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    (directory / "deep-competitor-library.md").write_text(render_deep_markdown(deep_report) + "\n", encoding="utf-8")


def base_result(task: dict[str, Any], mode: str, command: list[Any]) -> dict[str, Any]:
    return {
        "taskId": task.get("id", ""),
        "materialId": task.get("materialId", ""),
        "priority": task.get("priority"),
        "platform": task.get("platform", ""),
        "title": task.get("title", ""),
        "url": task.get("url", ""),
        "mode": mode,
        "command": display_command([str(item) for item in command]),
    }


def validate_public_capture_url(url: str, allow_localhost: bool) -> str:
    parsed = urllib.parse.urlparse(url)
    if parsed.scheme not in {"http", "https"} or not parsed.netloc:
        return "URL is not a public HTTP(S) URL."
    host = parsed.hostname or ""
    if host in {"localhost", "127.0.0.1", "::1"} and not allow_localhost:
        return "Localhost URLs are blocked unless --allow-localhost is supplied for fixtures/tests."
    lowered = url.lower()
    if any(marker in lowered for marker in ["/login", "/signin", "/captcha", "/challenge", "/editor", "/draft", "/preview"]):
        return "URL looks like login, captcha, editor, draft, or preview flow."
    return ""


def summarize_results(results: list[dict[str, Any]]) -> dict[str, Any]:
    statuses: dict[str, int] = {}
    modes: dict[str, int] = {}
    imported = 0
    for result in results:
        statuses[str(result.get("status", "unknown"))] = statuses.get(str(result.get("status", "unknown")), 0) + 1
        modes[str(result.get("mode", "unknown"))] = modes.get(str(result.get("mode", "unknown")), 0) + 1
        imported += int(result.get("recordCount") or 0)
    return {"statuses": dict(sorted(statuses.items())), "modes": dict(sorted(modes.items())), "importedRecords": imported}


def aggregate_deep_records(records: list[dict[str, Any]]) -> dict[str, Any]:
    platforms = sorted({str(record.get("platform") or "unknown") for record in records})
    pattern_counts: dict[str, int] = {}
    for record in records:
        for pattern in record.get("reusablePatterns", []):
            pattern_counts[str(pattern)] = pattern_counts.get(str(pattern), 0) + 1
    return {
        "platforms": platforms,
        "titles": [record.get("title", "") for record in records[:10]],
        "recordsWithObservedMetrics": sum(1 for record in records if record.get("visibleMetrics")),
        "patternCounts": dict(sorted(pattern_counts.items())),
    }


def report_dir(out_dir: Path) -> Path:
    return out_dir / COMPETITOR_DIR


def render_evidence_request(task: dict[str, Any]) -> str:
    lines = [
        "# Follow-Up Evidence Request",
        "",
        f"- Task: {task.get('id', '')}",
        f"- Material: {task.get('materialId', '')}",
        f"- Platform: {task.get('platform', '')}",
        f"- Title: {task.get('title', '')}",
        f"- URL: {task.get('url') or 'missing'}",
        f"- Mode: `{task.get('mode', '')}`",
        f"- Reason: {task.get('reason', '')}",
        "",
        "## Required Evidence",
    ]
    for item in task.get("requiredEvidence", []):
        lines.append(f"- {item}")
    lines.extend(
        [
            "",
            "## Safe Import Command",
            "",
            "Use copied browser-visible text, transcript, or official/user export only.",
            "",
            "```bash",
            f"python scripts/competitor_intake.py --text-file \"<visible-evidence.txt>\" --platform {task.get('platform', 'auto')} --out-dir \"<promotion-output>\"",
            "```",
        ]
    )
    return "\n".join(lines)


def render_results_markdown(report: dict[str, Any]) -> str:
    lines = [
        "# Follow-Up Capture Results",
        "",
        f"- Generated: {report['generatedAt']}",
        f"- Dry run: {report['dryRun']}",
        f"- Tasks: {report['recordCount']}",
        f"- Imported records: {report['summary']['importedRecords']}",
        "",
        "## Results",
    ]
    for result in report["results"]:
        lines.extend(
            [
                "",
                f"### {result.get('taskId', 'task')} - {result.get('platform', '')}",
                f"- Status: `{result.get('status', '')}`",
                f"- Mode: `{result.get('mode', '')}`",
                f"- Title: {result.get('title', '')}",
                f"- URL: {result.get('url') or 'unknown'}",
                f"- Imported records: {result.get('recordCount', 0)}",
            ]
        )
        if result.get("reason"):
            lines.append(f"- Reason: {result['reason']}")
        if result.get("evidenceRequest"):
            lines.append(f"- Evidence request: {result['evidenceRequest']}")
    lines.extend(["", "## Guardrails"])
    lines.extend(f"- {item}" for item in report["guardrails"])
    return "\n".join(lines)


def render_deep_markdown(report: dict[str, Any]) -> str:
    lines = [
        "# Deep Competitor Library",
        "",
        f"- Generated: {report['generatedAt']}",
        f"- Records: {report['recordCount']}",
        f"- Platforms: {', '.join(report['aggregatePatterns']['platforms']) if report['aggregatePatterns']['platforms'] else 'none'}",
        "",
        "## Records",
    ]
    for record in report["records"]:
        lines.extend(
            [
                "",
                f"### {record.get('id', 'record')} - {record.get('title', '')}",
                f"- Platform: {record.get('platform', '')}",
                f"- Creator: {record.get('creatorName') or 'unknown'}",
                f"- URL: {record.get('url') or 'unknown'}",
                f"- Hook: {record.get('hook') or 'needs manual review'}",
                f"- CTA: {record.get('cta') or 'none observed'}",
            ]
        )
    lines.extend(["", "## Guardrails"])
    lines.extend(f"- {item}" for item in report["guardrails"])
    return "\n".join(lines)


def guardrails() -> list[str]:
    return [
        "Only public URL capture candidates are fetched automatically.",
        "Manual/browser-assisted tasks require user-provided visible text, screenshots, transcripts, official APIs, or exports.",
        "Do not bypass captcha, login prompts, account verification, platform rate limits, or risk controls.",
        "Do not store cookies, passwords, API keys, OAuth tokens, or hidden browser tokens.",
        "Do not fabricate views, likes, comments, orders, revenue, or published URLs.",
    ]


def display_command(command: list[str]) -> list[str]:
    return ["python" if item == sys.executable else item for item in command]


def tail(value: str, limit: int = 1200) -> str:
    value = value.strip()
    return value if len(value) <= limit else value[-limit:]


def safe_slug(value: str) -> str:
    return re.sub(r"[^a-zA-Z0-9_.-]+", "-", value.strip()).strip("-") or "follow-up"


if __name__ == "__main__":
    main()
