#!/usr/bin/env python3
"""Render a simple MP4 promo video from generated platform content."""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import textwrap
from pathlib import Path
from typing import Any


def main() -> None:
    args = parse_args()
    ffmpeg = shutil.which("ffmpeg")
    if not ffmpeg:
        raise SystemExit("ffmpeg is required to render MP4 video. Install ffmpeg or run on a machine that has it in PATH.")
    content = load_content(args)
    title, segments = build_segments(content, args.platform)
    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    work_dir = out_path.parent / f"{out_path.stem}-assets"
    work_dir.mkdir(parents=True, exist_ok=True)
    ass_path = work_dir / "captions.ass"
    ass_path.write_text(render_ass(title, segments, args.width, args.height), encoding="utf-8")
    duration = max(segment["end"] for segment in segments)
    command = [
        ffmpeg,
        "-y",
        "-f",
        "lavfi",
        "-i",
        f"color=c=0x111827:s={args.width}x{args.height}:d={duration}",
        "-f",
        "lavfi",
        "-i",
        f"anullsrc=channel_layout=stereo:sample_rate=48000:d={duration}",
        "-vf",
        "subtitles=captions.ass",
        "-c:v",
        "libx264",
        "-pix_fmt",
        "yuv420p",
        "-c:a",
        "aac",
        "-shortest",
        str(out_path),
    ]
    subprocess.run(command, check=True, cwd=work_dir)
    metadata = {
        "video": str(out_path),
        "captions": str(ass_path),
        "platform": args.platform,
        "durationSeconds": duration,
        "segments": segments,
        "notes": [
            "This is a deterministic draft MP4 with silent audio and burned-in text.",
            "Use it as a review artifact or placeholder; replace with real voiceover and visuals before final publication.",
        ],
    }
    (out_path.with_suffix(".json")).write_text(json.dumps(metadata, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Video written to: {out_path.resolve()}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Render an MP4 draft from generated promotion content.")
    parser.add_argument("--content-json", required=True, help="Path to platform-content JSON generated by promotion_manager.py.")
    parser.add_argument("--platform", default="douyin", help="Platform key to render from the content JSON.")
    parser.add_argument("--out", default="./promotion-output/videos/promo-draft.mp4")
    parser.add_argument("--width", type=int, default=1280)
    parser.add_argument("--height", type=int, default=720)
    return parser.parse_args()


def load_content(args: argparse.Namespace) -> dict[str, Any]:
    data = json.loads(Path(args.content_json).read_text(encoding="utf-8"))
    if args.platform not in data:
        available = ", ".join(sorted(data))
        raise SystemExit(f"Platform '{args.platform}' not found. Available: {available}")
    return data[args.platform]


def build_segments(content: dict[str, Any], platform: str) -> tuple[str, list[dict[str, Any]]]:
    title = content.get("title") or f"{platform} promotion draft"
    storyboard = content.get("storyboard") or []
    if storyboard:
        segments = []
        for index, item in enumerate(storyboard):
            start, end = parse_time_range(item.get("time", ""), index)
            text = f"{item.get('visual', '')}\n{item.get('voiceover', '')}".strip()
            segments.append({"start": start, "end": end, "text": text or title})
        return title, segments
    voiceover = content.get("voiceover") or content.get("shortVideoScript") or content.get("description") or title
    chunks = chunk_text(voiceover, 45)
    segments = []
    current = 0
    for chunk in chunks[:6]:
        segments.append({"start": current, "end": current + 4, "text": chunk})
        current += 4
    return title, segments or [{"start": 0, "end": 5, "text": title}]


def parse_time_range(value: str, index: int) -> tuple[int, int]:
    try:
        start_text, end_text = value.lower().replace("s", "").split("-", 1)
        return int(start_text), int(end_text)
    except (ValueError, AttributeError):
        start = index * 4
        return start, start + 4


def chunk_text(value: str, width: int) -> list[str]:
    normalized = " ".join(value.split())
    if not normalized:
        return []
    return textwrap.wrap(normalized, width=width, break_long_words=False, replace_whitespace=False)


def render_ass(title: str, segments: list[dict[str, Any]], width: int, height: int) -> str:
    lines = [
        "[Script Info]",
        "ScriptType: v4.00+",
        f"PlayResX: {width}",
        f"PlayResY: {height}",
        "",
        "[V4+ Styles]",
        "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding",
        "Style: Title,Arial,52,&H00FFFFFF,&H000000FF,&H00222222,&H90000000,1,0,0,0,100,100,0,0,1,2,1,8,80,80,64,1",
        "Style: Body,Arial,40,&H00FFFFFF,&H000000FF,&H00222222,&H90000000,0,0,0,0,100,100,0,0,1,2,1,5,100,100,70,1",
        "",
        "[Events]",
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
        f"Dialogue: 0,0:00:00.00,{ass_time(max(segment['end'] for segment in segments))},Title,,0,0,0,,{escape_ass(title)}",
    ]
    for segment in segments:
        text = "\\N".join(chunk_text(segment["text"], 32))
        lines.append(f"Dialogue: 1,{ass_time(segment['start'])},{ass_time(segment['end'])},Body,,0,0,0,,{escape_ass(text)}")
    return "\n".join(lines)


def ass_time(seconds: int) -> str:
    minutes, sec = divmod(int(seconds), 60)
    hours, minutes = divmod(minutes, 60)
    return f"{hours}:{minutes:02d}:{sec:02d}.00"


def escape_ass(value: str) -> str:
    return value.replace("{", "(").replace("}", ")")


if __name__ == "__main__":
    main()
